# Generated by Django 4.2.6 on 2023-11-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=20)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("price", models.FloatField()),
            ],
        ),
    ]
