# Generated by Django 4.2.6 on 2023-11-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
