# Generated by Django 4.2.6 on 2023-11-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("productapp", "0002_alter_product_date_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("invoice_id", models.AutoField(primary_key=True, serialize=False)),
                ("client_name", models.CharField(max_length=50)),
                ("date_created", models.DateTimeField(auto_now=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Bank Transfer", "Bank Transfer"),
                            ("POS", "POS"),
                            ("Cash", "Cash"),
                        ],
                        default="Cash",
                        max_length=50,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Credit", "Credit"),
                            ("Paid", "Paid"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("agent", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="productapp.invoice",
            ),
        ),
    ]
