# Generated by Django 4.2.6 on 2023-11-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productapp", "0004_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("Pack(s)", "Pack(s)"),
                    ("Piece(s)", "Piece(s)"),
                    ("Kg", "Kg"),
                ],
                default="Piece(s)",
                max_length=50,
            ),
        ),
    ]
