# Generated by Django 4.2.6 on 2023-11-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productapp", "0005_product_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="client_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
