# Generated by Django 4.2.6 on 2023-11-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productapp", "0006_invoice_client_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="uniqueId",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="uniqueId",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="agent",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="client_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="date_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bank Transfer", "Bank Transfer"),
                    ("POS", "POS"),
                    ("Cash", "Cash"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="date_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
