# Generated by Django 4.2.6 on 2023-11-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productapp", "0007_invoice_last_updated_invoice_uniqueid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
