# Generated by Django 4.2.6 on 2024-01-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productapp", "0008_invoice_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="total_price",
        ),
        migrations.AddField(
            model_name="product",
            name="price_per_Qty",
            field=models.FloatField(default=0.0),
        ),
    ]
