# Generated by Django 4.2.6 on 2024-01-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productapp", "0009_rename_price_product_total_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_per_Qty",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="total_price",
            field=models.FloatField(default=0.0),
        ),
    ]
